In [27]:

import nltk
nltk.download('gutenberg')
from nltk.corpus import gutenberg
import pandas as pd


[nltk_data] Downloading package gutenberg to
[nltk_data]     C:\Users\PC\AppData\Roaming\nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!


In [28]:
df=gutenberg.raw('shakespeare-hamlet.txt')
with open('hamlet.txt','w') as file:
    file.write(df)

In [43]:
import pandas as pd
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split



In [30]:
with open('hamlet.txt','r') as file:
    text=file.read().lower()

In [31]:

tokenizer=Tokenizer()
tokenizer.fit_on_texts([text])

In [32]:
tokenizer

In [33]:
total_words=len(tokenizer.word_index)+1

In [34]:
total_words

4818

In [35]:
tokenizer.word_index

{'the': 1,
 'and': 2,
 'to': 3,
 'of': 4,
 'i': 5,
 'you': 6,
 'a': 7,
 'my': 8,
 'it': 9,
 'in': 10,
 'that': 11,
 'ham': 12,
 'is': 13,
 'not': 14,
 'his': 15,
 'this': 16,
 'with': 17,
 'your': 18,
 'but': 19,
 'for': 20,
 'me': 21,
 'lord': 22,
 'as': 23,
 'what': 24,
 'he': 25,
 'be': 26,
 'so': 27,
 'him': 28,
 'haue': 29,
 'king': 30,
 'will': 31,
 'no': 32,
 'our': 33,
 'we': 34,
 'on': 35,
 'are': 36,
 'if': 37,
 'all': 38,
 'then': 39,
 'shall': 40,
 'by': 41,
 'thou': 42,
 'come': 43,
 'or': 44,
 'hamlet': 45,
 'good': 46,
 'do': 47,
 'hor': 48,
 'her': 49,
 'let': 50,
 'now': 51,
 'thy': 52,
 'how': 53,
 'more': 54,
 'they': 55,
 'from': 56,
 'enter': 57,
 'at': 58,
 'was': 59,
 'oh': 60,
 'like': 61,
 'most': 62,
 'there': 63,
 'well': 64,
 'know': 65,
 'selfe': 66,
 'would': 67,
 'them': 68,
 'loue': 69,
 'may': 70,
 "'tis": 71,
 'vs': 72,
 'sir': 73,
 'qu': 74,
 'which': 75,
 'did': 76,
 'why': 77,
 'laer': 78,
 'giue': 79,
 'thee': 80,
 'ile': 81,
 'must': 82,
 'hath': 

In [36]:
input_sequences=[]
for line in text.split('\n'):
    token_list=tokenizer.texts_to_sequences([line])[0]
    for i in range(1,len(token_list)):
        n_gram_sequence=token_list[:i+1]
        input_sequences.append(n_gram_sequence)

In [37]:
input_sequences

[[1, 687],
 [1, 687, 4],
 [1, 687, 4, 45],
 [1, 687, 4, 45, 41],
 [1, 687, 4, 45, 41, 1886],
 [1, 687, 4, 45, 41, 1886, 1887],
 [1, 687, 4, 45, 41, 1886, 1887, 1888],
 [1180, 1889],
 [1180, 1889, 1890],
 [1180, 1889, 1890, 1891],
 [57, 407],
 [57, 407, 2],
 [57, 407, 2, 1181],
 [57, 407, 2, 1181, 177],
 [57, 407, 2, 1181, 177, 1892],
 [407, 1182],
 [407, 1182, 63],
 [408, 162],
 [408, 162, 377],
 [408, 162, 377, 21],
 [408, 162, 377, 21, 247],
 [408, 162, 377, 21, 247, 882],
 [18, 66],
 [451, 224],
 [451, 224, 248],
 [451, 224, 248, 1],
 [451, 224, 248, 1, 30],
 [408, 407],
 [451, 25],
 [408, 6],
 [408, 6, 43],
 [408, 6, 43, 62],
 [408, 6, 43, 62, 1893],
 [408, 6, 43, 62, 1893, 96],
 [408, 6, 43, 62, 1893, 96, 18],
 [408, 6, 43, 62, 1893, 96, 18, 566],
 [451, 71],
 [451, 71, 51],
 [451, 71, 51, 1894],
 [451, 71, 51, 1894, 567],
 [451, 71, 51, 1894, 567, 378],
 [451, 71, 51, 1894, 567, 378, 80],
 [451, 71, 51, 1894, 567, 378, 80, 3],
 [451, 71, 51, 1894, 567, 378, 80, 3, 273],
 [451, 71

In [38]:
print(text.split('\n'))

['[the tragedie of hamlet by william shakespeare 1599]', '', '', 'actus primus. scoena prima.', '', 'enter barnardo and francisco two centinels.', '', "  barnardo. who's there?", '  fran. nay answer me: stand & vnfold', 'your selfe', '', '   bar. long liue the king', '', '   fran. barnardo?', '  bar. he', '', '   fran. you come most carefully vpon your houre', '', "   bar. 'tis now strook twelue, get thee to bed francisco", '', "   fran. for this releefe much thankes: 'tis bitter cold,", 'and i am sicke at heart', '', '   barn. haue you had quiet guard?', '  fran. not a mouse stirring', '', '   barn. well, goodnight. if you do meet horatio and', 'marcellus, the riuals of my watch, bid them make hast.', 'enter horatio and marcellus.', '', "  fran. i thinke i heare them. stand: who's there?", '  hor. friends to this ground', '', '   mar. and leige-men to the dane', '', '   fran. giue you good night', '', "   mar. o farwel honest soldier, who hath relieu'd you?", "  fra. barnardo ha's my 

In [39]:
max_sequence_len=max([len(x) for x in input_sequences])

In [40]:
max_sequence_len

14

In [45]:
import numpy as np


In [47]:
input_sequences=np.array(pad_sequences(input_sequences,maxlen=max_sequence_len,padding='pre'))

In [48]:
input_sequences

array([[   0,    0,    0, ...,    0,    1,  687],
       [   0,    0,    0, ...,    1,  687,    4],
       [   0,    0,    0, ...,  687,    4,   45],
       ...,
       [   0,    0,    0, ...,    4,   45, 1047],
       [   0,    0,    0, ...,   45, 1047,    4],
       [   0,    0,    0, ..., 1047,    4,  193]], dtype=int32)

In [51]:
X,y=input_sequences[:,:-1],input_sequences[:,-1]

In [52]:
X

array([[   0,    0,    0, ...,    0,    0,    1],
       [   0,    0,    0, ...,    0,    1,  687],
       [   0,    0,    0, ...,    1,  687,    4],
       ...,
       [   0,    0,    0, ...,  687,    4,   45],
       [   0,    0,    0, ...,    4,   45, 1047],
       [   0,    0,    0, ...,   45, 1047,    4]], dtype=int32)

In [53]:
y


array([ 687,    4,   45, ..., 1047,    4,  193], dtype=int32)

In [54]:
import tensorflow as tf
y=tf.keras.utils.to_categorical(y,num_classes=total_words)

In [55]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [59]:
print(X.shape, y.shape)

(25732, 13) (25732, 4818)


In [60]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [67]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense,Dropout 
model=Sequential()
model.add(Embedding(total_words, 100, input_length=max_sequence_len-1))
model.add(LSTM(150, return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(150))
model.add(Dense(total_words, activation='softmax'))

In [68]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])


In [69]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_2 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_3 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [70]:
model.fit(X_train, y_train, epochs=100, verbose=1, validation_data=(X_test, y_test))

Epoch 1/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 26s 35ms/step - accuracy: 0.0318 - loss: 7.1207 - val_accuracy: 0.0338 - val_loss: 6.6888
Epoch 2/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 32s 50ms/step - accuracy: 0.0387 - loss: 6.4534 - val_accuracy: 0.0394 - val_loss: 6.7510
Epoch 3/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 30s 47ms/step - accuracy: 0.0435 - loss: 6.3491 - val_accuracy: 0.0501 - val_loss: 6.7972
Epoch 4/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 25s 39ms/step - accuracy: 0.0549 - loss: 6.1259 - val_accuracy: 0.0530 - val_loss: 6.8298
Epoch 5/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 26s 40ms/step - accuracy: 0.0564 - loss: 6.0031 - val_accuracy: 0.0591 - val_loss: 6.8834
Epoch 6/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 26s 40ms/step - accuracy: 0.0654 - loss: 5.8160 - val_accuracy: 0.0610 - val_loss: 6.9307
Epoch 7/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 26s 40ms/step - accuracy: 0.0744 - loss: 5.6701 - val_accuracy: 0.0631 - val_loss: 7.0023
Epoch 8/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 26s 40ms/step - accuracy: 0.0822 - loss: 5

In [72]:
def predict_next_word(model, tokenizer, text, max_sequence_len):
    token_list = tokenizer.texts_to_sequences([text])[0]
    token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
    predicted = model.predict(token_list, verbose=0)
    predicted_word_index = np.argmax(predicted, axis=-1)[0]
    return tokenizer.index_word[predicted_word_index]

In [84]:
input_text = "Speake of it. Stay, and speake. Stop it  "
predicted_word = predict_next_word(model, tokenizer, input_text, max_sequence_len)

In [85]:
print(f"Predicted next word for '{input_text}': {predicted_word}")

Predicted next word for 'Speake of it. Stay, and speake. Stop it  ': to


In [86]:
model.save('lstm_model.h5')

In [87]:
import pickle
with open('tokenizer.pickle', 'wb') as handle:
    pickle.dump(tokenizer, handle, protocol=pickle.HIGHEST_PROTOCOL)